dashboard:
    path:     /
    defaults:
        _controller: 'CTIC\App\Dashboard\Infrastructure\DashboardController'
        _controller_method: 'indexAction'
        _controller_create: 'CTIC\App\Dashboard\Application\CreateDashboardController'

login:
    path:     /login
    defaults:
        _controller: 'CTIC\App\User\Infrastructure\LoginController'
        _controller_method: 'loginAction'
        _controller_create: 'CTIC\App\User\Application\CreateLoginController'

logout:
    path:     /logout
    defaults:
        _controller: 'CTIC\App\User\Infrastructure\LoginController'
        _controller_method: 'logoutAction'
        _controller_create: 'CTIC\App\User\Application\CreateLoginController'

#Device

GET_dispositivos_listado:
    path:     /dispositivos/listado
    defaults:
        _controller: 'CTIC\Device\Device\Infrastructure\DeviceController'
        _controller_method: 'indexAction'
        _controller_create: 'CTIC\Device\Device\Application\CreateDeviceController'

GET_dispositivos_mostrar:
    path:     /dispositivos/mostrar/{id}
    defaults:
        _controller: 'CTIC\Device\Device\Infrastructure\DeviceController'
        _controller_method: 'showAction'
        _controller_create: 'CTIC\Device\Device\Application\CreateDeviceController'

GET_dispositivos_crear:
    path:     /dispositivos/crear
    methods:  [GET, POST]
    defaults:
        _controller: 'CTIC\Device\Device\Infrastructure\DeviceController'
        _controller_method: 'createAction'
        _controller_create: 'CTIC\Device\Device\Application\CreateDeviceController'

GET_dispositivos_modificar:
    path:     /dispositivos/modificar/{id}
    methods:  [GET, POST]
    defaults:
        _controller: 'CTIC\Device\Device\Infrastructure\DeviceController'
        _controller_method: 'updateAction'
        _controller_create: 'CTIC\Device\Device\Application\CreateDeviceController'

POST_dispositivos_eliminar:
    path:     /dispositivos/eliminar/{id}
    methods:  [POST]
    defaults:
        _controller: 'CTIC\Device\Device\Infrastructure\DeviceController'
        _controller_method: 'deleteAction'
        _controller_create: 'CTIC\Device\Device\Application\CreateDeviceController'

POST_dispositivos_eliminargrupo:
    path:     /dispositivos/eliminargrupo
    methods:  [POST]
    defaults:
        _controller: 'CTIC\Device\Device\Infrastructure\DeviceController'
        _controller_method: 'bulkDeleteAction'
        _controller_create: 'CTIC\Device\Device\Application\CreateDeviceController'

POST_dispositivos_descargar:
    path:     /dispositivos/descargar
    methods:  [POST]
    defaults:
        _controller: 'CTIC\Device\Device\Infrastructure\DeviceController'
        _controller_method: 'downloadAction'
        _controller_create: 'CTIC\Device\Device\Application\CreateDeviceController'
